# Generated by Django 2.2.6 on 2019-11-04 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('content', models.CharField(default='', max_length=200)),
                ('is_use', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'zsh_article',
            },
        ),
    ]
