# Generated by Django 2.2.6 on 2019-10-28 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=20, unique=True)),
                ('p_age', models.IntegerField(default=10)),
                ('p_sex', models.BooleanField(default=True)),
            ],
        ),
    ]
